### ISSUE TITLE
My thoughts about StatusLine(NC)? group, change the background

### ISSUE THREAD

**Issue by kutsan** [cocopon/iceberg.vim#23]
I think background of the status line should be darker and its foreground should be gray like this. What do you think about that? It's still okay if you don't think it's good. I also wanted to ask what is the reason behind making all background color bright. I don't know if it's just me but currently it doesn't look good. This is just a feedback.

![](https://i.imgur.com/Ks8fKbQ.png)

```vim
highlight! StatusLine guibg=#818596 guifg=#1e2132
highlight! StatusLineNC guibg=#3e445e guifg=#1e2132
```

**Comment by cocopon** [comment]
Thank you for the feedback! I'm considering about visibility of an edge between vertically-split windows and carefully picked these colors. For example:

## darker:
<img width="690" alt="2018-02-13 18 27 43" src="https://user-images.githubusercontent.com/602961/36145853-fb6afdf6-10f5-11e8-8059-a0967b9877c5.png">

## current:
<img width="690" alt="2018-02-13 18 28 14" src="https://user-images.githubusercontent.com/602961/36145868-06eb2282-10f6-11e8-84f1-b4d027dfea6e.png">

**Comment by kutsan** [comment]
I think in my version it's still obvious which pane is active. After then that, do I really need a more obvious indicator which pane is really active. It's rather distracting. I mean, when you press <kbd>C-w h</kbd> you know which pane will be active next. Again, that's my opinion. I think your project is awesome, there are some of the details I don't like, I already did override them for my likings.

**Comment by cocopon** [comment]
I partially agree with you, but **at least for now** I still feel the current version is good. Maybe it is important for me to recognize edges of windows clearly because I use Vim with heavily-split windows.

<img width="1433" alt="2018-02-14 10 11 53" src="https://user-images.githubusercontent.com/602961/36183458-b252084a-1171-11e8-906e-73932775e3c0.png">
<img width="1433" alt="2018-02-14 10 13 20" src="https://user-images.githubusercontent.com/602961/36183459-b4f8852e-1171-11e8-8ec6-03f8ba015e16.png">

There are as many color preferences as there are people. Satisfying everyone with single color scheme is impossible. You can fork the repository or modify the coloration as you did.

**Comment by kutsan** [comment]
Thanks for you kind answers. I also partially agree with you. I don't use splits as much as you do, so it's rather pointless for me to make that bright. But in the screenshots, I see clearly why you choosed that way. I'm closing the issue, thanks again!
